version: "3"
services:
# 启动mysql
  gbserver:
    container_name: gbserver
    restart: unless-stopped
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
    ports:
      - "13306:3306"
    networks:
      - gb-net
    volumes:
      - gb-db-data:/var/lib/mysql
# 启动redis
  gbredis:
    container_name: gbredis
    restart: unless-stopped
    image: redis:latest
    ports:
      - "16379:6379"
    networks:
      - gb-net
    volumes:
      - gb-redis-data:/data

# 启动ZLMediaKit
  gbzlm:
    container_name: gbzlm
    restart: unless-stopped
    image: zlmediakit/zlmediakit:master
    env_file:
      - .env
    ports:
      - "11935:1935"
      - "8080:80"
      - "8554:554"
      - "10000:10000"
      - "10000:10000/udp"
      - "8000:8000/udp"
      - "20000-20300:20000-20300"
      - "20000-20300:20000-20300/udp"
    networks:
      - gb-net

volumes:
  gb-db-data:
  gb-redis-data:
  media-data:

networks:
  gb-net:
    driver: bridge