version: "3"
services:
  gbserver:
    container_name: gbserver
    restart: unless-stopped
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
    volumes:
      - gb-data:/var/lib/mysql
    ports:
      - "13306:3306"
    networks:
      - gb-net

volumes:
  gb-data:

networks:
  gb-net:
    driver: bridge